### ISSUE TITLE
Update CKAN configurable text if applicable

### ISSUE THREAD

**Issue by nyarly** [hackforla/accessthedata-ckan#6]

**Comment by nyarly** [comment]
@TonyDelgadoWillis Do you remember what this one is? IIRC, you were suggesting it was likely not applicable?

**Comment by TonyDelgadoWillis** [comment]
Had to restart docker because of some database issues, but the configurable options listed at https://docs.ckan.org/en/2.10/sysadmin-guide.html#customizing-look-and-feel have mostly been overwritten by the AccessTheData extension. The only fields that appear to have an effect are "Site Title" (which changes the Alt text for the homepage logo) and "Custom CSS" (which works as originally intended to inject CSS onto the page). This is probably not something we can work from at the moment as we match the design. At some point, we will probably want to restore reading from these values so that other orgs that want to use the template can easily override some AtD-specific text.
